name: Terraform Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-security-review:
    name: Security Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Terraform Security Analysis
        uses: stakpak/stakpak-action@v1.0.10
        with:
          api_key: ${{ secrets.STAKPAK_API_KEY }}
          prompt: |
            Review this Terraform code for security vulnerabilities and best practices violations,
            then write a summary of the findings and provide a list of recommendations for fixing the issues.
          max_steps: 10
          verbose: true
          workdir: .
